/** UpQuiz design tokens extracted from the Stitch output */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#002045",
        "primary-container": "#1a365d",
        "on-primary": "#ffffff",
        "on-primary-container": "#86a0cd",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#adc7f7",
        secondary: "#13696a",
        "secondary-container": "#a2eded",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#1a6d6e",
        "secondary-fixed": "#a5eff0",
        "secondary-fixed-dim": "#89d3d4",
        tertiary: "#002337",
        "tertiary-container": "#003957",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#54a5df",
        "tertiary-fixed": "#cbe6ff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        background: "#f7fafc",
        "on-background": "#181c1e",
        surface: "#f7fafc",
        "surface-bright": "#f7fafc",
        "surface-dim": "#d7dadc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f6",
        "surface-container": "#ebeef0",
        "surface-container-high": "#e5e9eb",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "on-surface": "#181c1e",
        "on-surface-variant": "#43474e",
        outline: "#74777f",
        "outline-variant": "#c4c6cf",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eef1f3",
        "inverse-primary": "#adc7f7",
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      fontFamily: {
        headline: ["Public Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
