import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import Layout, { Icon } from "../components/Layout";
import QuestionPrompt from "../components/QuestionPrompt";
import { api, Question, Subject } from "../api";

interface BankGroup {
  group_type: "exam" | "generated";
  title: string;
  exam_id?: string;
  status?: string;
  exam_mode?: "take_home" | "live";
  total_points?: number;
  questions: Question[];
}

function optionText(value: unknown): string {
  if (value == null) return "";
  if (typeof value === "string") return value;
  try { return JSON.stringify(value); } catch { return String(value); }
}

export default function QuestionBank() {
  const [subjectId, setSubjectId] = useState("");
  const { data: subjects = [] } = useQuery({
    queryKey: ["subjects"],
    queryFn: () => api.get<Subject[]>("/subjects"),
  });
  const sid = subjectId || subjects[0]?.id || "";
  const { data, isLoading } = useQuery<{ groups: BankGroup[] }>({
    queryKey: ["question-bank", sid],
    queryFn: () => api.get<{ groups: BankGroup[] }>(`/subjects/${sid}/question-bank`),
    enabled: !!sid,
  });
  const groups = data?.groups || [];
  const totalQuestions = groups.reduce((sum, group) => sum + group.questions.length, 0);

  return (
    <Layout title="Question Bank">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-6">
        <div>
          <h2 className="font-headline text-2xl text-primary">Question Bank</h2>
          <p className="text-sm text-on-surface-variant mt-1">
            Generated questions are grouped here, including questions already added to each quiz.
          </p>
        </div>
        <div className="min-w-72">
          <label className="text-sm font-semibold text-on-surface">Subject</label>
          <select
            value={sid}
            onChange={(event) => setSubjectId(event.target.value)}
            className="mt-1.5 w-full border border-outline-variant rounded-lg px-3 py-2.5 bg-white"
          >
            {subjects.map((subject) => (
              <option key={subject.id} value={subject.id}>{subject.code} - {subject.name}</option>
            ))}
          </select>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <Stat icon="quiz" label="Groups" value={groups.length} />
        <Stat icon="help" label="Questions" value={totalQuestions} />
        <Stat icon="book" label="Subject" value={subjects.find((subject) => subject.id === sid)?.code || "-"} />
      </div>

      {isLoading ? (
        <p className="text-on-surface-variant">Loading question bank...</p>
      ) : groups.length === 0 ? (
        <p className="text-on-surface-variant">No question bank entries yet.</p>
      ) : (
        <div className="space-y-5">
          {groups.map((group) => (
            <section key={`${group.group_type}-${group.exam_id || "generated"}`} className="bg-surface-container-lowest border border-outline-variant rounded-xl overflow-hidden">
              <div className="px-6 py-4 bg-surface-container-low border-b border-outline-variant flex flex-col md:flex-row md:items-center justify-between gap-3">
                <div>
                  <div className="flex items-center gap-2">
                    <Icon name={group.group_type === "exam" ? "assignment" : "auto_awesome"} className="text-secondary" />
                    <h3 className="font-headline text-lg font-bold text-primary">{group.title}</h3>
                  </div>
                  <p className="text-xs text-on-surface-variant mt-1">
                    {group.group_type === "exam"
                      ? `${group.exam_mode?.replace("_", " ") || "exam"} - ${group.status || "draft"}`
                      : "Questions generated by AI before or after exam creation"}
                  </p>
                </div>
                <span className="text-xs font-bold uppercase text-on-surface-variant">{group.questions.length} question{group.questions.length === 1 ? "" : "s"}</span>
              </div>
              <div className="divide-y divide-outline-variant">
                {group.questions.map((question, index) => (
                  <QuestionRow key={question.id} question={question} index={index} />
                ))}
                {group.questions.length === 0 && (
                  <p className="p-6 text-sm text-on-surface-variant">No questions in this group yet.</p>
                )}
              </div>
            </section>
          ))}
        </div>
      )}
    </Layout>
  );
}

function Stat({ icon, label, value }: { icon: string; label: string; value: string | number }) {
  return (
    <div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-5 flex items-center gap-4">
      <div className="w-11 h-11 rounded-lg bg-secondary-container text-secondary flex items-center justify-center">
        <Icon name={icon} />
      </div>
      <div>
        <p className="text-xs uppercase tracking-widest text-on-surface-variant font-bold">{label}</p>
        <p className="font-headline text-xl font-bold text-primary">{value}</p>
      </div>
    </div>
  );
}

function QuestionRow({ question, index }: { question: Question; index: number }) {
  return (
    <article className="p-5">
      <div className="flex flex-col md:flex-row md:items-start gap-4">
        <span className="w-8 h-8 rounded bg-primary text-on-primary flex items-center justify-center font-bold text-sm shrink-0">
          {index + 1}
        </span>
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2 mb-2">
            <span className="px-2 py-1 rounded-full bg-surface-container-high text-xs font-semibold text-on-surface-variant">{question.type.replace("_", " ")}</span>
            <span className="px-2 py-1 rounded-full bg-secondary-container text-xs font-semibold text-on-secondary-container">{question.difficulty}</span>
            <span className="px-2 py-1 rounded-full bg-surface-container-high text-xs font-semibold text-on-surface-variant">{question.points} pts</span>
            {question.topic && <span className="px-2 py-1 rounded-full bg-primary-container/20 text-xs font-semibold text-primary">{question.topic}</span>}
            {question.status && <span className="px-2 py-1 rounded-full bg-green-100 text-xs font-semibold text-green-800">{question.status}</span>}
          </div>
          <QuestionPrompt
            prompt={question.prompt}
            imageUrl={question.image_url}
            className="space-y-2 font-semibold text-on-surface leading-6"
            imageWrapperClassName="mt-3 rounded-lg border border-outline-variant bg-surface-container-low p-2"
          />
          <AnswerPreview question={question} />
        </div>
      </div>
    </article>
  );
}

function AnswerPreview({ question }: { question: Question }) {
  if (question.type === "mcq" && Array.isArray(question.options)) {
    const correct = question.answer?.correct_index;
    return (
      <div className="grid md:grid-cols-2 gap-2 mt-3">
        {question.options.map((option: unknown, index: number) => (
          <div key={index} className={`rounded-lg border px-3 py-2 text-sm ${correct === index ? "border-secondary bg-secondary-container/30 text-secondary font-semibold" : "border-outline-variant text-on-surface-variant"}`}>
            {String.fromCharCode(65 + index)}. {optionText(option)}
          </div>
        ))}
      </div>
    );
  }
  if (question.type === "true_false") {
    return <p className="text-sm text-secondary mt-3 font-semibold">Correct answer: {question.answer?.correct ? "True" : "False"}</p>;
  }
  if (question.type === "fill_blank") {
    return <p className="text-sm text-secondary mt-3 font-semibold">Accepted: {(question.answer?.accepted || []).join(", ")}</p>;
  }
  if (question.type === "essay") {
    return <p className="text-sm text-on-surface-variant mt-3">Rubric: {optionText(question.answer?.rubric || question.answer)}</p>;
  }
  if (question.type === "matching") {
    return <p className="text-sm text-on-surface-variant mt-3">Matching answer pairs are stored for grading.</p>;
  }
  return null;
}
